python/django/buy_online_hub/buy_online_hub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, URLResolver

urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
]

# Проверяем, находится ли проект в режиме отладки.
if settings.DEBUG:
    # Если проект находится в режиме отладки, добавляем URL-пути для отладочной панели веб-инструментов.
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    # Затем добавляем URL-пути для медиафайлов к urlpatterns.
    # Это нужно для того, чтобы в режиме отладки Django мог обслуживать медиафайлы.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/django/buy_online_hub/main/urls.py
from django.urls import path, URLPattern

from main.views import index, about, delivery_and_payment, contacts

# Задаем имя для данного приложения, которое будет использоваться для различения его URL-адресов от URL-адресов других
# приложений.
app_name = 'main'

# Определение маршрутов URL для представлений
urlpatterns: list[URLPattern] = [
    # Главная страница, вызывает функцию index из файла views.py
    path('', index, name='index'),

    # Страница "О нас", вызывает функцию about из файла views.py
    path('about/', about, name='about'),

    # Страница "Доставка и оплата", вызывает функцию delivery_and_payment из файла views.py
    path('delivery_and_payment/', delivery_and_payment, name='delivery_and_payment'),

    # Страница "Контакты", вызывает функцию contacts из файла views.py
    path('contacts/', contacts, name='contacts'),
]

python/django/buy_online_hub/users/urls.py
from django.urls import path, URLPattern

from users.views import login, registration, profile, logout

# Задаем имя для данного приложения, которое будет использоваться для различения его URL-адресов от URL-адресов других
# приложений.
app_name = 'users'

# Определение маршрутов URL для представлений
urlpatterns: list[URLPattern] = [

    path('login/', login, name='login'),

    path('registration/', registration, name='registration'),

    path('profile/', profile, name='profile'),

    path('logout/', logout, name='logout'),
]

python/django/buy_online_hub/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        # Настройки метаданных модели
        db_table: str = 'user'  # Имя таблицы в базе данных
        verbose_name: str = 'пользователя'  # Отображаемое название модели в единственном числе
        verbose_name_plural: str = 'пользователи'  # Отображаемое название модели во множественном числе

        # Метод для представления объекта в виде строки

    def __str__(self) -> str:
        return self.username

python/django/buy_online_hub/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя',
        widget=forms.TextInput(attrs={'autofocus': True,
                                      'class': 'form-control',
                                      'placeholder': 'Введите ваше имя пользователя'})
    )

    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'class': 'form-control',
                                          'placeholder': 'Введите ваше пароль'})
    )

    class Mena:
        model = User
        fields: list[str] = ['username', 'password']

python/django/buy_online_hub/users/views.py
from typing import Any

from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from users.forms import UserLoginForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username: Any = request.POST['username']
            password: Any = request.POST['password']
            user: AbstractBaseUser | None = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context: dict[str, Any] = {
        'title': 'Home - Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    context = {
        'title': 'Home - Регистрация',
    }
    return render(request, 'users/registration.html', context)


def profile(request):
    context = {
        'title': 'Home - Кабинет',
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    pass

python/django/buy_online_hub/users/templates/users/login.html
<!-- Текущий шаблон будет наследовать (расширять) базовый шаблон base.html, расположенный в приложении main. 
 Наследование шаблонов в Django позволяет определить общий макет и структуру для нескольких страниц, а затем вставлять
 специфичный контент в определенные места базового шаблона. -->
{% extends "base.html" %}

<!-- Эта строка в Django-шаблоне загружает тег-библиотеку static, которая предоставляет тег для ссылок на статические
 файлы. Использование этого тега предпочтительнее, чем жестко закодированные URL-адреса, так как он позволяет Django
 правильно формировать ссылки на статические файлы в зависимости от настроек проекта и режима работы (разработка 
 или production). -->
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url "user:login" %}" method="post">
                        {% csrf_token %}
                    
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" name="username" id="id_username"
                                   placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" name="password" id="id_password" 
                                   placeholder="Введите ваш пароль" required>
                        </div>
                        
{#                        {% for i in form %}#}
{#                             <div class="mb-3">}#}
{#                                <label for="{{ i.id_for_label }}" class="form-label">{{ i.label }}</label>#}
{#                                {{ i }}#}
{#                             </div>>#}
{#                        {% endfor %}#}
                    
{#                        <div class="mb-3">#}
{#                            <label for="username" class="form-label">Имя пользователя</label>#}
{#                            <input type="text" class="form-control" id="username"#}
{#                                   placeholder="Введите ваше имя пользователя" required>#}
{#                        </div>#}
{#                        <div class="mb-3">#}
{#                            <label for="password" class="form-label">Пароль</label>#}
{#                            <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль"#}
{#                                   required>#}
{#                        </div>#}
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "/deps/icons/google.svg" %}" alt="Catalog Icon" width="16"
                                 height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "/deps/icons/facebook.svg" %}" alt="Catalog Icon"
                                 width="16"
                                 height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "/deps/icons/github.svg" %}" alt="Catalog Icon" width="16"
                                 height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

python/django/buy_online_hub/users/templates/users/profile.html
<!-- Текущий шаблон будет наследовать (расширять) базовый шаблон base.html, расположенный в приложении main. 
 Наследование шаблонов в Django позволяет определить общий макет и структуру для нескольких страниц, а затем вставлять
 специфичный контент в определенные места базового шаблона. -->
{% extends "base.html" %}

<!-- Эта строка в Django-шаблоне загружает тег-библиотеку static, которая предоставляет тег для ссылок на статические
 файлы. Использование этого тега предпочтительнее, чем жестко закодированные URL-адреса, так как он позволяет Django
 правильно формировать ссылки на статические файлы в зависимости от настроек проекта и режима работы (разработка 
 или production). -->
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form>
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    <img src="{% static "/deps/images/baseavatar.jpg" %}"
                                         alt="Аватар пользователя" class="img-fluid rounded-circle"
                                         style="max-width: 150px;">
                                    <input type="file" class="form-control mt-3" id="avatar"
                                           accept="image/*">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="firstName" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" id="firstName"
                                           placeholder="Введите ваше имя" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="lastName" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" id="lastName"
                                           placeholder="Введите вашу фамилию" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" id="username"
                                           placeholder="Введите ваше имя пользователя" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="email"
                                           placeholder="Введите ваш email *youremail@example.com" value=""
                                           required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Корзина</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            <!-- Закончилась разметка корзины -->
                        </div>
                        <a class="btn btn-dark" href="../orders/create_order.html">
                            Оформить заказ
                        </a>
                    </div>
                </div>
                <!-- Оформленные заказы -->
                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои заказы</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading1">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                data-bs-target="#collapse1" aria-expanded="false"
                                                aria-controls="collapse1">
                                            Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В
                                            обработке</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse1" class="accordion-collapse collapse show"
                                         aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Комплект стол и три стула</a>
                                                    </td>
                                                    <td>1</td>
                                                    <td>255.00 $</td>
                                                    <td>255.00 $</td>

                                                </tr>
                                                </tbody>
                                            </table>
                                            <div class="d-flex justify-content-between">
                                                <p><strong>Итого:</strong></p>
                                                <p><strong>255.00 $</strong></p>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading2">
                                        <button class="accordion-button collapsed" type="button"
                                                data-bs-toggle="collapse" data-bs-target="#collapse2"
                                                aria-expanded="false" aria-controls="collapse2">
                                            Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2"
                                         data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стул офисный</a></td>
                                                    <td>2</td>
                                                    <td>30.00 $</td>
                                                    <td>60.00 $</td>

                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Закончилась разметка заказов -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

python/django/buy_online_hub/users/templates/users/registration.html
<!-- Текущий шаблон будет наследовать (расширять) базовый шаблон base.html, расположенный в приложении main. 
 Наследование шаблонов в Django позволяет определить общий макет и структуру для нескольких страниц, а затем вставлять
 специфичный контент в определенные места базового шаблона. -->
{% extends "base.html" %}

<!-- Эта строка в Django-шаблоне загружает тег-библиотеку static, которая предоставляет тег для ссылок на статические
 файлы. Использование этого тега предпочтительнее, чем жестко закодированные URL-адреса, так как он позволяет Django
 правильно формировать ссылки на статические файлы в зависимости от настроек проекта и режима работы (разработка 
 или production). -->
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="firstName"
                                       placeholder="Введите ваше имя" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="lastName"
                                       placeholder="Введите вашу фамилию" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="username"
                                       placeholder="Введите ваше имя пользователя" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="email"
                                       placeholder="Введите ваш email" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" id="password1"
                                       placeholder="Введите пароль" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="password2"
                                       placeholder="Подтвердите пароль" required>
                            </div>
                        </div>
                        <button type="submit"
                                class="btn btn-dark btn-block">Зарегистрироваться
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}